wallets:
  uphold-contribution: 'uphold-contribution'
  gemini-contribution: 'gemini-contribution'
  uphold-referral: 'uphold-referral'
  gemini-referral: 'gemini-referral'
  bitflyer-default: 'bitflyer-default'
