[[constraint]]
  name = "github.com/go-chi/chi"
  version = "3.3.0"

[[constraint]]
  name = "github.com/pressly/lg"
  version = "1.0.0"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "1.0.3"

[[constraint]]
  name = "github.com/garyburd/redigo"
  version = "1.3.0"

[[constraint]]
  name = "github.com/satori/go.uuid"
  version = "1.1.0"

[[constraint]]
  name = "github.com/prometheus/client_golang"
  version = "0.9.0-pre1"

[[constraint]]
  name = "github.com/shopspring/decimal"
  branch = "master"

[[constraint]]
  name = "github.com/asaskevich/govalidator"
  version = "8.0.0"

[[constraint]]
  name = "github.com/square/go-jose"
  version = "2.1.3"

[[constraint]]
  name = "github.com/btcsuite/btcutil"
  version = "BTCUTIL_0_5_0"

[[constraint]]
  name = "github.com/ethereum/go-ethereum"
  version = "1.7.2"
