version: "3.4"

networks:
  skus:
    driver: bridge

services:
  # dev-refresh service will start up a rewards server bound to host port 3343
  # which allows one to do `docker restart rewards-dev-refresh` when the user
  # wants to "restart" the service running new code.  This is especially helpful
  # when you hook it up to `fswatch` type utilities, causing a re-run of `go run`
  # every time a file changes.
  skus-dev-refresh:
    container_name: skus-dev-refresh
    image: golang:1.22
    ports:
      - "3353:3353"
      - "6061:6061"
    command: "go run main.go serve skus rest"
    volumes:
      - ../:/src
      - ../test/secrets:/etc/kafka/secrets
    working_dir: /src
    networks:
      - skus
      - grant
    depends_on:
      - postgres
    environment:
      - PPROF_ENABLED=true
      - ENV=local
      - DEBUG=1
      - CHALLENGE_BYPASS_SERVER=http://challenge-bypass:2416
      - CHALLENGE_BYPASS_TOKEN
      - "DATABASE_MIGRATIONS_URL=file:///src/migrations"
      - "DATABASE_URL=postgres://grants:password@postgres/grants?sslmode=disable"
      - ENCRYPTION_KEY=MTIzNDU2Nzg5MDEyMzQ1Njc4OTAxMjM0
      - KAFKA_BROKERS=kafka:19092
      - KAFKA_SSL_CA_LOCATION=/etc/kafka/secrets/snakeoil-ca-1.crt
      - KAFKA_SSL_CERTIFICATE_LOCATION=/etc/kafka/secrets/consumer-ca1-signed.pem
      - KAFKA_SSL_KEY_LOCATION=/etc/kafka/secrets/consumer.client.key
      - KAFKA_SSL_KEY_PASSWORD=confluent
      - KAFKA_REQUIRED_ACKS=1
      - TOKEN_LIST
