version: "3.4"

services:
  # payment-refresh service will start up a grant server bound to host port 3333
  # which allows one to do `docker restart grant-payment-refresh` when the user
  # wants to "restart" the service running new code.  This is especially helpful
  # when you hook it up to `fswatch` type utilities, causing a re-run of `go run`
  # every time a file changes.
  payment-refresh:
    container_name: grant-payment-refresh
    image: golang:1.22
    ports:
      - "3335:3333"
      - "6061:6061"
    # payments runs in grants right now, not split out into own command yet
    command: "go run main.go serve grant"
    volumes:
      - .:/src
      - ./test/secrets:/etc/kafka/secrets
    working_dir: /src
    depends_on:
      - kafka
      - postgres
      - challenge-bypass
    networks:
      - grant
    environment:
      - GOTOOLCHAIN=local
      - ADDR=:3333
      - PPROF_ENABLED=true
      - ENABLE_LINKING_DRAINING=true
      - ENV=local
      - DEBUG=1
      - BAT_SETTLEMENT_ADDRESS
      - BRAVE_TRANSFER_PROMOTION_ID
      - CHALLENGE_BYPASS_SERVER=http://challenge-bypass:2416
      - CHALLENGE_BYPASS_TOKEN
      - FEATURE_WALLET=true
      - "DATABASE_MIGRATIONS_URL=file:///src/migrations"
      - "DATABASE_URL=postgres://grants:password@postgres/grants?sslmode=disable"
      - ENCRYPTION_KEY=MTIzNDU2Nzg5MDEyMzQ1Njc4OTAxMjM0
      - FEATURE_PAYMENT=true
      - DONOR_WALLET_CARD_ID
      - DONOR_WALLET_PRIVATE_KEY
      - DONOR_WALLET_PUBLIC_KEY
      - GRANT_SIGNATOR_PUBLIC_KEY
      - GRANT_WALLET_CARD_ID
      - GRANT_WALLET_PRIVATE_KEY
      - GRANT_WALLET_PUBLIC_KEY
      - KAFKA_BROKERS=kafka:19092
      - KAFKA_SSL_CA_LOCATION=/etc/kafka/secrets/snakeoil-ca-1.crt
      - KAFKA_SSL_CERTIFICATE_LOCATION=/etc/kafka/secrets/consumer-ca1-signed.pem
      - KAFKA_SSL_KEY_LOCATION=/etc/kafka/secrets/consumer.client.key
      - KAFKA_SSL_KEY_PASSWORD=confluent
      - KAFKA_REQUIRED_ACKS=1
      - TOKEN_LIST
      - UPHOLD_ACCESS_TOKEN
      - "RATIOS_SERVICE=https://ratios.rewards.bravesoftware.com"
      - RATIOS_TOKEN
